from pathlib import Path
import re


def edit(path, fn):
    p=Path(path); text=p.read_text(encoding='utf-8'); new=fn(text)
    if new==text: raise SystemExit(f'No changes made to {path}')
    p.write_text(new,encoding='utf-8')


def rep(text, old, new, label):
    if old not in text: raise SystemExit(f'Missing {label}: {old[:120]!r}')
    return text.replace(old,new,1)


def plugin(text):
    text=rep(text,"  import PlaceSearch from './PlaceSearch.svelte';","  import PlaceSearch from './PlaceSearch.svelte';\n  import V21Panel from './V21Panel.svelte';",'V21 import')
    text=rep(text,"  import { nextWintryEvent } from './eventOutlook';","  import { nextWintryEvent } from './eventOutlook';\n  import { formatElevation, formatPrecip, formatSnow, loadUnitSystem, type UnitSystem } from './displayUnits';",'units import')
    text=rep(text,"    <PlaceSearch on:select={handlePlaceSelect} on:clear={handleSearchClear} />","    <PlaceSearch on:select={handlePlaceSelect} on:clear={handleSearchClear} />\n    <V21Panel bind:unitSystem {activeRunTime} on:select={handleV21Select} />",'V21 panel')
    text=rep(text,"    bind:tab={forecastTab}\n    on:close={() => chartOpen = false}","    bind:tab={forecastTab}\n    units={unitSystem}\n    on:close={() => chartOpen = false}",'chart units prop')
    text=rep(text,"  const FAVOURITES_STORAGE_KEY = 'snowline:favourites:v1', FAVOURITES_CHANGED_EVENT = 'wintry:favourites-changed';","  const FAVOURITES_STORAGE_KEY = 'snowline:favourites:v1', FAVOURITES_CHANGED_EVENT = 'wintry:favourites-changed', PREFS_STORAGE_KEY='wintry:prefs:v1';",'prefs key')
    text=rep(text,"  let enabled=true, panelHidden=false, infoOpen=false, chartOpen=false, forecastTab:'graph'|'sounding'='graph', viewportLoading=false, refreshQueued=false, probeLoading=false;","  let enabled=true, panelHidden=false, infoOpen=false, chartOpen=false, forecastTab:'graph'|'sounding'='graph', viewportLoading=false, refreshQueued=false, probeLoading=false, unitSystem:UnitSystem='metric', prefsReady=false;",'prefs vars')
    text=rep(text,"  function statusForDifference(d:number):ProbeStatus{return d>POSITION_NEAR_SNOWLINE_METRES?'above':d<-POSITION_NEAR_SNOWLINE_METRES?'below':'near'}\n  function positionText(d:number){const x=Math.round(Math.abs(d)/10)*10,a=Math.abs(d);if(a<=POSITION_NEAR_SNOWLINE_METRES)return`<strong>Near snowline</strong><small>within ±${POSITION_NEAR_SNOWLINE_METRES} m</small>`;const side=d>0?'above':'below',label=a>1000?`Far ${side} snowline`:a>300?`Well ${side} snowline`:`Slightly ${side} snowline`;return`<strong>${label}</strong><small>${x} m ${side}</small>`}","  function statusForDifference(d:number):ProbeStatus{return d>POSITION_NEAR_SNOWLINE_METRES?'above':d<-POSITION_NEAR_SNOWLINE_METRES?'below':'near'}\n  function positionText(d:number){const a=Math.abs(d);if(a<=POSITION_NEAR_SNOWLINE_METRES)return`<strong>Near snowline</strong><small>within ±${formatElevation(POSITION_NEAR_SNOWLINE_METRES,unitSystem)}</small>`;const side=d>0?'above':'below',label=a>1000?`Far ${side} snowline`:a>300?`Well ${side} snowline`:`Slightly ${side} snowline`;return`<strong>${label}</strong><small>${formatElevation(a,unitSystem)} ${side}</small>`}",'position units')
    old="  function metricTile(label:string,value:string,className=''){return`<span class=\"${className}\"><small>${label}</small><strong>${value}</strong></span>`}\n  function compactEventLine(point:CachedPoint,terrainM:number,target:number){const event=nextWintryEvent(point,terrainM,target);if(!event)return'No wintry event through +144 h';const when=event.activeNow?'Current event':`Next · ${shortValid(event.startTime)}`,snow=formatNewSnowCm(event.newSnowCm),low=event.minSnowlineM!==null?` · min SL ${event.minSnowlineM} m`:'';return`${when} · ${event.dominantPhase.label} · ${snow}${low}`}\n  function labelGrid(args:LabelGridArgs){\n    const terrain=metricTile('Terrain',`${args.terrain} m`,'metric-terrain');\n    const snowline=metricTile('Snowline',`${args.snowline} m`,'metric-snowline');\n    const relation=`<div class=\"snowline-compact-relation\">${positionText(args.difference)}<span>${args.hasPrecip&&args.precip!==null?`Precip ${formatPrecipMm(args.precip)} mm/3h`:'Dry'}</span></div>`;"
    new="  function metricTile(label:string,value:string,className=''){return`<span class=\"${className}\"><small>${label}</small><strong>${value}</strong></span>`}\n  function compactEventLine(point:CachedPoint,terrainM:number,target:number){const event=nextWintryEvent(point,terrainM,target);if(!event)return'No wintry event through +144 h';const when=event.activeNow?'Current event':`Next · ${shortValid(event.startTime)}`,snow=formatSnow(event.newSnowCm,unitSystem),low=event.minSnowlineM!==null?` · min SL ${formatElevation(event.minSnowlineM,unitSystem)}`:'',confidence=` · ${event.confidence[0].toUpperCase()}${event.confidence.slice(1)}`;return`${when} · ${event.dominantPhase.label} · ${snow}${low}${confidence}`}\n  function labelGrid(args:LabelGridArgs){\n    const terrain=metricTile('Terrain',formatElevation(args.terrain,unitSystem),'metric-terrain');\n    const snowline=metricTile('Snowline',formatElevation(args.snowline,unitSystem),'metric-snowline');\n    const relation=`<div class=\"snowline-compact-relation\">${positionText(args.difference)}<span>${args.hasPrecip&&args.precip!==null?`Precip ${formatPrecip(args.precip,unitSystem)}`:'Dry'}</span></div>`;"
    text=rep(text,old,new,'label units')
    text=rep(text,"const marker=L.marker([lat,lon],{interactive:true,bubblingMouseEvents:false,zIndexOffset:2000,icon:L.divIcon({className:`snowline-click-label snowline-probe-${status}${dry?' snowline-card-dry':''}`","const hazard=/FREEZING RAIN|ICE PELLETS/.test(mainText);const marker=L.marker([lat,lon],{interactive:true,bubblingMouseEvents:false,zIndexOffset:2000,icon:L.divIcon({className:`snowline-click-label snowline-probe-${status}${dry?' snowline-card-dry':''}${hazard?' snowline-card-hazard':''}`",'hazard card')
    # share text units
    text=text.replace("`Snowline: ${snowline!==null?`${Math.round(snowline/10)*10} m`:'Unavailable'}`","`Snowline: ${snowline!==null?formatElevation(snowline,unitSystem):'Unavailable'}`")
    text=text.replace("`Terrain: ${clickedMapElevationM!==null?`${Math.round(clickedMapElevationM/10)*10} m`:'Unavailable'}`","`Terrain: ${clickedMapElevationM!==null?formatElevation(clickedMapElevationM,unitSystem):'Unavailable'}`")
    text=text.replace("`Precipitation: ${precip!==null?`${formatPrecipMm(precip)} mm/3h`:'Unavailable'}`","`Precipitation: ${precip!==null?formatPrecip(precip,unitSystem):'Unavailable'}`")
    text=text.replace("`Event minimum snowline: ${event.minSnowlineM} m`","`Event minimum snowline: ${formatElevation(event.minSnowlineM,unitSystem)}`")
    text=text.replace("`Event peak precipitation: ${formatPrecipMm(event.peakPrecipMm3h)} mm/3h`","`Event peak precipitation: ${formatPrecip(event.peakPrecipMm3h,unitSystem)}`")
    text=text.replace("`Event estimated new snow: ${formatNewSnowCm(event.newSnowCm)}`","`Event estimated new snow: ${formatSnow(event.newSnowCm,unitSystem)}`")
    # saved overview selection handler
    text=rep(text,"  function handleSearchClear(){if(pointSource==='search'&&!chartOpen)clearPointState(true)}","  function handleV21Select(event:CustomEvent<PlaceSelection>){handlePlaceSelect(event)}\n  function handleSearchClear(){if(pointSource==='search'&&!chartOpen)clearPointState(true)}",'V21 select')
    # preference helpers before map navigation
    anchor="  function handleMapNavigation(){if(!enabled)return;if(moveTimer)clearTimeout(moveTimer);moveTimer=setTimeout(refreshViewport,350)}"
    helpers="  function loadPreferences(){try{const p=JSON.parse(localStorage.getItem(PREFS_STORAGE_KEY)||'{}');if(typeof p.enabled==='boolean')enabled=p.enabled;if(typeof p.panelHidden==='boolean')panelHidden=p.panelHidden;if(p.forecastTab==='graph'||p.forecastTab==='sounding')forecastTab=p.forecastTab}catch{}unitSystem=loadUnitSystem();prefsReady=true}\n  function persistPreferences(){if(!prefsReady)return;try{localStorage.setItem(PREFS_STORAGE_KEY,JSON.stringify({enabled,panelHidden,forecastTab}))}catch{}}\n  $: if(prefsReady){enabled;panelHidden;forecastTab;unitSystem;persistPreferences()}\n\n"+anchor
    text=rep(text,anchor,helpers,'prefs helpers')
    text=rep(text,"  onMount(()=>{map.on('moveend',handleMapNavigation);","  onMount(()=>{loadPreferences();map.on('moveend',handleMapNavigation);",'load prefs')
    # hazard CSS
    text=rep(text,":global(.snowline-probe-near>span){background:linear-gradient(180deg,rgba(29,27,11,.99),rgba(17,16,9,.99))}",":global(.snowline-probe-near>span){background:linear-gradient(180deg,rgba(29,27,11,.99),rgba(17,16,9,.99))}:global(.snowline-card-hazard>span){border-top-color:#c184ff!important;box-shadow:0 0 0 1px rgba(193,132,255,.35),0 12px 32px rgba(77,27,107,.58)}:global(.snowline-card-hazard>span>b){color:#e7c8ff!important;background:rgba(174,91,230,.12)!important}",'hazard css')
    return text


def chart(text):
    text=rep(text,"  import { nextWintryEvent } from './eventOutlook';","  import { nextWintryEvent } from './eventOutlook';\n  import { elevationImpactOutlook, type ElevationOutlookRow } from './elevationOutlook';\n  import { formatElevation, formatPrecip, formatSnow, type UnitSystem } from './displayUnits';",'chart imports')
    text=rep(text,"  export let tab: 'graph' | 'sounding' = 'graph';","  export let tab: 'graph' | 'sounding' = 'graph';\n  export let units: UnitSystem = 'metric';",'chart units export')
    text=rep(text,"  $: event = nextWintryEvent(point, terrainM, timestamp);\n  $: chart = buildChart(point, terrainM, timestamp, crossing?.crossingTime ?? null, realNow);","  $: event = nextWintryEvent(point, terrainM, timestamp);\n  $: elevationOutlook = elevationImpactOutlook(point, terrainM, timestamp);\n  $: elevationRows = compactElevationRows(elevationOutlook?.rows ?? [], terrainM);\n  $: chart = buildChart(point, terrainM, timestamp, crossing?.crossingTime ?? null, realNow);",'elevation reactive')
    text=rep(text,"  function terrainPosition(difference: number | null): string { if (difference === null) return ''; const value = Math.round(Math.abs(difference) / 10) * 10; if (difference > 100) return `${value} m above snowline`; if (difference < -100) return `${value} m below snowline`; return 'Terrain near snowline'; }","  function terrainPosition(difference: number | null): string { if (difference === null) return ''; const value = formatElevation(Math.abs(difference), units); if (difference > 100) return `${value} above snowline`; if (difference < -100) return `${value} below snowline`; return 'Terrain near snowline'; }\n  function confidenceText(value:string){return `${value[0].toUpperCase()}${value.slice(1)} confidence`}\n  function compactElevationRows(rows:ElevationOutlookRow[],terrain:number|null){if(terrain===null||!rows.length)return rows.slice(0,5);return [...rows].sort((a,b)=>Math.abs(a.elevationM-terrain)-Math.abs(b.elevationM-terrain)).slice(0,5).sort((a,b)=>a.elevationM-b.elevationM)}",'terrain position')
    # dynamic section units
    text=text.replace('SNOWLINE <tspan>m</tspan>',"SNOWLINE <tspan>{units === 'imperial' ? 'ft' : 'm'}</tspan>")
    text=text.replace('PRECIPITATION <tspan>mm/3h</tspan>',"PRECIPITATION <tspan>{units === 'imperial' ? 'in/3h' : 'mm/3h'}</tspan>")
    text=text.replace('NEW SNOW <tspan>est. cm</tspan>',"NEW SNOW <tspan>{units === 'imperial' ? 'est. in' : 'est. cm'}</tspan>")
    text=text.replace('<text x="195" y="301" text-anchor="middle" class="empty-band">0 cm</text>',"<text x=\"195\" y=\"301\" text-anchor=\"middle\" class=\"empty-band\">{units === 'imperial' ? '0 in' : '0 cm'}</text>")
    # tooltip/current metric formatting
    text=text.replace("{tooltip.snowline !== null ? `${tooltip.snowline} m` : '—'}","{formatElevation(tooltip.snowline, units)}")
    text=text.replace("{tooltip.precip !== null ? `${formatPrecipMm(tooltip.precip)} mm/3h` : '—'}","{formatPrecip(tooltip.precip, units)}")
    text=text.replace("{formatNewSnowCm(tooltip.newSnow)}","{formatSnow(tooltip.newSnow, units)}")
    text=text.replace("{Math.round(terrainM / 10) * 10} m","{formatElevation(terrainM, units)}")
    text=text.replace("{chart.currentSnowline !== null ? `${chart.currentSnowline} m` : '—'}","{formatElevation(chart.currentSnowline, units)}")
    text=text.replace("{chart.currentPrecip !== null ? `${formatPrecipMm(chart.currentPrecip)} mm/3h` : '—'}","{formatPrecip(chart.currentPrecip, units)}")
    # replace event card block
    old='''    <div class="outlook24 event-intelligence">\n      <b>{event?.activeNow ? 'Current wintry event' : 'Next wintry event'}</b>\n      {#if event}\n        <span>{event.dominantPhase.icon} {event.dominantPhase.label} · {formatEventRange(event.startTime, event.endTime)}</span>\n        <span>Min snowline {event.minSnowlineM !== null ? `${event.minSnowlineM} m` : '—'} · Peak precip {formatPrecipMm(event.peakPrecipMm3h)} mm/3h · New snow {formatNewSnowCm(event.newSnowCm)}</span>\n        {#if !event.activeNow}<button type="button" title="Jump to event start" on:click={jumpToEvent}>Go to event →</button>{/if}\n      {:else}\n        <span>No terrain-relevant wintry precipitation detected through +144 h.</span>\n      {/if}\n    </div>'''
    new='''    <div class="outlook24 event-intelligence" class:event-hazard={event?.dominantPhase.key === 'freezing-rain' || event?.dominantPhase.key === 'ice-pellets'}>\n      <div class="event-head"><b>{event?.activeNow ? 'Current wintry event' : 'Next wintry event'}</b>{#if event}<i class={`confidence confidence-${event.confidence}`}>{confidenceText(event.confidence)}</i>{/if}</div>\n      {#if event}\n        <span class="event-phase">{event.dominantPhase.icon} {event.dominantPhase.label} · {formatEventRange(event.startTime, event.endTime)}</span>\n        <span>Min snowline {formatElevation(event.minSnowlineM, units)} · Peak precip {formatPrecip(event.peakPrecipMm3h, units)} · New snow {formatSnow(event.newSnowCm, units)}</span>\n        <div class="event-timeline"><span><small>Start</small>{formatShortTime(event.startTime)}</span><span><small>Peak</small>{formatShortTime(event.peakTime)}</span><span><small>End</small>{formatShortTime(event.endTime)}</span></div>\n        {#if !event.activeNow}<button type="button" title="Jump to event start" on:click={jumpToEvent}>Go to event →</button>{/if}\n      {:else}\n        <span>No terrain-relevant wintry precipitation detected through +144 h.</span>\n      {/if}\n    </div>\n    {#if elevationOutlook && elevationRows.length}\n      <div class="elevation-impact">\n        <div class="elevation-head"><b>Elevation impact</b>{#if elevationOutlook.snowFavouredAboveM !== null}<span>Snow favoured ≥ {formatElevation(elevationOutlook.snowFavouredAboveM, units)}</span>{/if}</div>\n        {#if elevationOutlook.marginalBandLowM !== null && elevationOutlook.marginalBandHighM !== null}<div class="impact-band">Marginal band {formatElevation(elevationOutlook.marginalBandLowM, units)}–{formatElevation(elevationOutlook.marginalBandHighM, units)}</div>{/if}\n        <div class="elevation-grid">{#each elevationRows as row}<span class:terrain-row={terrainM !== null && Math.abs(row.elevationM-terrainM)<80}><b>{formatElevation(row.elevationM, units)}</b><small>{row.event ? row.event.dominantPhase.label : 'No event'}</small><em>{row.event ? formatSnow(row.event.newSnowCm, units) : '—'}</em></span>{/each}</div>\n      </div>\n    {/if}'''
    text=rep(text,old,new,'event card')
    text=rep(text,"    <SoundingChart {point} {terrainM} {placeName} embedded={true} />","    <SoundingChart {point} {terrainM} {placeName} units={units} embedded={true} />",'sounding units')
    # BuildChart labels
    text=text.replace("minLabel: `${Math.round(min)} m`, midLabel: `${Math.round((min + max) / 2)} m`, maxLabel: `${Math.round(max)} m`","minLabel: formatElevation(min, units), midLabel: formatElevation((min + max) / 2, units), maxLabel: formatElevation(max, units)")
    text=text.replace("precipMaxLabel: precipMax ? formatPrecipMm(precipMax) : '—'","precipMaxLabel: precipMax ? formatPrecip(precipMax, units).replace(/\\s*(mm|in)\\/3h$/, '') : '—'")
    text=text.replace("newSnowMaxLabel: formatNewSnowCm(newSnowMax).replace(' cm', '')","newSnowMaxLabel: formatSnow(newSnowMax, units)")
    # styles append before final media or end style
    css="\n  .event-head,.elevation-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.confidence{padding:2px 5px;border-radius:8px;font-size:6.5px;font-style:normal;font-weight:850}.confidence-high{background:rgba(96,211,139,.12);color:#87e5aa}.confidence-medium{background:rgba(255,209,84,.12);color:#f5d76d}.confidence-low{background:rgba(255,136,104,.12);color:#ffad96}.event-hazard{border-color:rgba(193,132,255,.38)!important;box-shadow:inset 3px 0 rgba(193,132,255,.8)}.event-timeline{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;margin-top:3px}.event-timeline span{padding:4px;border-radius:6px;background:rgba(255,255,255,.035);font-size:7px;font-weight:800;text-align:center}.event-timeline small{display:block;margin-bottom:2px;color:#71838d;font-size:5.8px;text-transform:uppercase}.elevation-impact{margin-top:6px;padding:7px;border:1px solid rgba(255,255,255,.08);border-radius:8px;background:rgba(255,255,255,.025)}.elevation-head b{font-size:8px}.elevation-head span,.impact-band{color:#87a7b7;font-size:6.8px}.impact-band{margin-top:3px}.elevation-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:3px;margin-top:5px}.elevation-grid span{padding:4px 2px;border-radius:6px;background:rgba(255,255,255,.035);text-align:center}.elevation-grid span.terrain-row{outline:1px solid rgba(255,190,112,.48);background:rgba(255,174,86,.07)}.elevation-grid b,.elevation-grid small,.elevation-grid em{display:block}.elevation-grid b{font-size:7px}.elevation-grid small{margin-top:2px;color:#9aabb4;font-size:5.7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.elevation-grid em{margin-top:2px;color:#dfeaf0;font-size:6.5px;font-style:normal;font-weight:800}\n"
    text=rep(text,"</style>",css+"</style>",'chart css')
    return text


def sounding(text):
    text=rep(text,"  import { precipMmAt, PRECIP_THRESHOLD_MM_H } from './precip';","  import { precipMmAt, PRECIP_THRESHOLD_MM_H } from './precip';\n  import { formatElevation, formatTemperature, type UnitSystem } from './displayUnits';",'sounding units import')
    text=rep(text,"  export let embedded = false;","  export let embedded = false;\n  export let units: UnitSystem = 'metric';",'sounding units export')
    text=rep(text,"    nodes: { tx: number; dx: number; y: number }[];","    nodes: { tx:number; dx:number; wx:number; y:number; pressure:number; height:number; temp:number; dew:number; wet:number }[];",'sounding node type')
    text=rep(text,"  let pinchDistance = 0;","  let pinchDistance = 0;\n  let hoverNode: {tx:number;dx:number;wx:number;y:number;pressure:number;height:number;temp:number;dew:number;wet:number;clientX:number;clientY:number}|null=null;",'hover state')
    text=rep(text,"    <div class=\"sounding-viewport\" bind:this={viewport} tabindex=\"0\" role=\"group\" aria-label=\"Zoomable forecast sounding\" on:wheel|preventDefault={handleWheel} on:pointerdown={startPlotPointer} on:pointermove={movePlotPointer} on:pointerup={endPlotPointer} on:pointercancel={endPlotPointer} on:dblclick={resetZoom} on:keydown={handleViewportKey}>","    <div class=\"sounding-viewport\" bind:this={viewport} tabindex=\"0\" role=\"group\" aria-label=\"Zoomable forecast sounding\" on:wheel|preventDefault={handleWheel} on:pointerdown={startPlotPointer} on:pointermove={movePlotPointer} on:pointerup={endPlotPointer} on:pointercancel={endPlotPointer} on:pointerleave={() => { if (!plotPointers.size) hoverNode = null; }} on:dblclick={resetZoom} on:keydown={handleViewportKey}>",'viewport hover')
    # add hover SVG after node circles loop
    old='''        {#each sounding.nodes as n}\n          <circle cx={n.tx} cy={n.y} r="2.1" class="temp-dot" />\n          <circle cx={n.dx} cy={n.y} r="2" class="dew-dot" />\n        {/each}'''
    new='''        {#each sounding.nodes as n}\n          <circle cx={n.tx} cy={n.y} r="2.1" class="temp-dot" />\n          <circle cx={n.dx} cy={n.y} r="2" class="dew-dot" />\n        {/each}\n        {#if hoverNode}\n          <line x1="48" x2="310" y1={hoverNode.y} y2={hoverNode.y} class="hover-level" />\n          <circle cx={hoverNode.tx} cy={hoverNode.y} r="4" class="hover-temp" />\n          <circle cx={hoverNode.dx} cy={hoverNode.y} r="4" class="hover-dew" />\n          <circle cx={hoverNode.wx} cy={hoverNode.y} r="4" class="hover-wet" />\n        {/if}'''
    text=rep(text,old,new,'hover svg')
    text=rep(text,"    </div>\n\n    <div class=\"key\">","    </div>\n    {#if hoverNode}<div class=\"sounding-hover\" style={`left:${Math.min(window.innerWidth-180,hoverNode.clientX+12)}px;top:${Math.max(8,hoverNode.clientY-82)}px`}><b>{Math.round(hoverNode.pressure)} hPa · {formatElevation(hoverNode.height,units)}</b><span>T {formatTemperature(hoverNode.temp,units)}</span><span>Td {formatTemperature(hoverNode.dew,units)}</span><span>Tw {formatTemperature(hoverNode.wet,units)}</span></div>{/if}\n\n    <div class=\"key\">",'hover tooltip')
    text=text.replace("<text x={g.x} y=\"360\" text-anchor=\"middle\" class=\"axis\">{g.value}°</text>","<text x={g.x} y=\"360\" text-anchor=\"middle\" class=\"axis\">{units === 'imperial' ? Math.round(g.value*9/5+32) : g.value}°</text>")
    # inspect function and move pointer
    text=rep(text,"  function movePlotPointer(event: PointerEvent) {\n    if (!viewport || !plotPointers.has(event.pointerId)) return;","  function inspectPointer(event:PointerEvent){if(!svgEl||!sounding)return;const rect=svgEl.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)return;const sy=(event.clientY-rect.top)/Math.max(1,rect.height)*390;const n=[...sounding.nodes].sort((a,b)=>Math.abs(a.y-sy)-Math.abs(b.y-sy))[0];if(n)hoverNode={...n,clientX:event.clientX,clientY:event.clientY}}\n  function movePlotPointer(event: PointerEvent) {\n    inspectPointer(event);\n    if (!viewport || !plotPointers.has(event.pointerId)) return;",'inspect pointer')
    text=rep(text,"    const nodes = profile.map(v => ({ tx: x(v.tempC), dx: x(v.dewpointC), y: y(v.heightM) }));","    const nodes = profile.map(v => ({ tx:x(v.tempC), dx:x(v.dewpointC), wx:x(v.wetBulbC), y:y(v.heightM), pressure:v.pressureHpa, height:v.heightM, temp:v.tempC, dew:v.dewpointC, wet:v.wetBulbC }));",'node data')
    text=text.replace("surfaceTw: diagnostics ? `${diagnostics.extrapolated ? '~' : ''}${diagnostics.wetBulbC.toFixed(1)}°C` : '—'","surfaceTw: diagnostics ? `${diagnostics.extrapolated ? '~' : ''}${formatTemperature(diagnostics.wetBulbC,units)}` : '—'")
    text=text.replace("snowline: snowlineM !== null ? `${Math.round(snowlineM / 10) * 10} m` : '—'","snowline: formatElevation(snowlineM,units)")
    text=rep(text,"    <div class=\"hint\">Phase diagnosis uses the selected time · wheel / pinch / +/- to zoom · drag to pan</div>","    <div class=\"hint\">Hover/touch for level details · wheel / pinch / +/- to zoom · drag to pan</div>",'sounding hint')
    css="\n  .hover-level{stroke:rgba(255,255,255,.45);stroke-width:.8;stroke-dasharray:2 2}.hover-temp{fill:#0d171d;stroke:#ff765f;stroke-width:2}.hover-dew{fill:#0d171d;stroke:#72d98b;stroke-width:2}.hover-wet{fill:#0d171d;stroke:#69d4ff;stroke-width:2}.sounding-hover{position:fixed;z-index:10060;display:grid;grid-template-columns:repeat(3,auto);gap:4px 8px;min-width:145px;padding:7px 8px;border:1px solid rgba(255,255,255,.16);border-radius:8px;background:rgba(5,10,14,.96);box-shadow:0 8px 22px rgba(0,0,0,.48);pointer-events:none}.sounding-hover b{grid-column:1/-1;color:#eaf5fa;font-size:8px}.sounding-hover span{color:#aebcc4;font-size:7px;font-weight:750}\n"
    text=rep(text,"</style>",css+"</style>",'sounding css')
    return text

edit('src/plugin.svelte',plugin)
edit('src/SnowlineChart.svelte',chart)
edit('src/SoundingChart.svelte',sounding)

# Version/metadata/docs.
p=Path('package.json'); t=p.read_text(encoding='utf-8'); t=t.replace('"version": "20.0.0"','"version": "21.0.0"',1); t=t.replace('v20 adds next-event intelligence through +144 h, summarising timing, dominant precipitation type, minimum snowline, peak precipitation and estimated new snow. The simplified point label now focuses on current terrain impact and one clear next-event line, with full graph and sounding detail one tap away.','v21 is the feature-complete terrain-aware winter forecast: next-event intelligence, confidence, event timeline, elevation impacts and snow by elevation, saved-place outlooks, Metric/Imperial units, model freshness, persistent preferences, hazard emphasis and detailed sounding inspection.',1); p.write_text(t,encoding='utf-8')

p=Path('src/pluginConfig.ts'); t=p.read_text(encoding='utf-8'); t=t.replace("version: '20.0.0'","version: '21.0.0'",1); t=re.sub(r"description: '.*?',\n  author:","description: 'v21 terrain-aware winter forecast: event confidence and timing, elevation impacts and snow by elevation, saved-place outlooks, Metric/Imperial units, ECMWF freshness, persistent preferences, hazard emphasis, graph and detailed hover/touch sounding inspection.',\n  author:",t,count=1); p.write_text(t,encoding='utf-8')

p=Path('README.md'); t=p.read_text(encoding='utf-8'); t=t.replace('**20.0.0**','**21.0.0**'); marker='## Current version'; addition='''## v21 feature-complete release\n\n- Metric / Imperial display units\n- ECMWF run freshness\n- Event confidence plus Start / Peak / End timeline\n- Elevation-impact guidance and estimated new snow by elevation\n- On-demand next-event outlook for saved places\n- Stronger freezing-rain / ice-pellet hazard emphasis\n- Persistent panel, enable/disable, tab and unit preferences\n- Hover/touch sounding inspection for pressure, height, temperature, dew point and wet bulb\n\n''';
if '## v21 feature-complete release' not in t and marker in t: t=t.replace(marker,addition+marker,1)
p.write_text(t,encoding='utf-8')
